image: node:12.18.2

.build: &build
- yarn
- yarn build

.setup: &setup
- npm install -g firebase-tools
- firebase use gjs-guide --token $FIREBASE_TOKEN

stages:
- build
- deploy

build:
  stage: build
  allow_failure: false
  when: always
  cache:
    paths:
    - node_modules/
  script:
  - *build
  artifacts:
    paths:
    - public

production:
  stage: deploy
  before_script:
    - *setup
    - *build
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
      allow_failure: false
  script:
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID | Build $CI_BUILD_ID" --non-interactive --only hosting:gjs-guide --token $FIREBASE_TOKEN